#ifndef TRACKIR_USERSPACE_USB_H
#define TRACKIR_USERSPACE_USB_H

#define TRACKIR_USB_VENDOR_ID 0x131Du
#define TRACKIR_USB_TIR5V2_PRODUCT_ID 0x0158u
#define TRACKIR_USB_TIR5V3_PRODUCT_ID 0x0159u
#define TRACKIR_USB_IS_SUPPORTED_PRODUCT_ID(product_id) \
  ((product_id) == TRACKIR_USB_TIR5V2_PRODUCT_ID || \
   (product_id) == TRACKIR_USB_TIR5V3_PRODUCT_ID)
#define TRACKIR_USB_CONFIGURATION_VALUE 1u
#define TRACKIR_USB_INTERFACE_NUMBER 0u
#define TRACKIR_USB_ALTERNATE_SETTING 0u

#endif /* TRACKIR_USERSPACE_USB_H */
