#ifndef TRACKIR_USERSPACE_USB_H
#define TRACKIR_USERSPACE_USB_H

#define TRACKIR_USB_VENDOR_ID 0x131Du
#define TRACKIR_USB_PRODUCT_ID 0x0158u
#define TRACKIR_USB_CONFIGURATION_VALUE 1u
#define TRACKIR_USB_INTERFACE_NUMBER 0u
#define TRACKIR_USB_ALTERNATE_SETTING 0u

#endif /* TRACKIR_USERSPACE_USB_H */
